name: aiden_admin
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  cloud_firestore: ^4.13.5
  file_picker: ^6.1.1
  firebase_auth: ^4.15.1
  firebase_storage: ^11.5.6
  firebase_storage_web: ^3.6.17
  flutter:
    sdk: flutter
  get: ^4.6.6
  google_fonts: ^6.1.0
  google_sign_in: ^6.1.6
  iconsax: ^0.0.8
  image_picker: ^1.0.4
  image_picker_web: ^3.1.1
  mime_type: ^1.0.0
  universal_html: ^2.2.4

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0

flutter:
  uses-material-design: true
  assets:
   - assets/images/
   - assets/jsons/
